# Generated by Django 4.0.5 on 2022-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartmodel_order_id_cartmodel_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='order_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='payment_id',
            new_name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='payment_signature',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
